### ISSUE TITLE
Show an error popup when there is problem in the server.

### ISSUE THREAD

**Issue by benevbright** [nishi-ai/softball-register-web#12]
<img width="1008" alt="Screenshot 2021-09-01 at 14 12 00" src="https://user-images.githubusercontent.com/916690/131669407-8f872ba4-a016-450a-818e-4eed22c29cc5.png">

This is not a validation error but something is happening on the server. (500)
However, in this case, webapp doesn't show anything to users because they're not validation errors. 
But we should show something otherwise they could misunderstand. Let's show alert popup for these "unknown" problem.

**Comment by nishi-ai** [comment]
![Screenshot 2021-09-05 at 11 12 19](https://user-images.githubusercontent.com/60405643/132121694-f3273e42-8688-4a92-8602-a12e590486ad.png)

An alert already is showing.

**Comment by benevbright** [comment]
@nishi-ai hm... yeah, right. 
Let me investigate it a bit more.
