### ISSUE TITLE
Create project in Vercel (Next.js)

### ISSUE THREAD

**Issue by benevbright** [nishi-ai/softball-register-web#61]
Vercel provides a deployment solution like Heroku did.

1. create an account and create a project in https://vercel.com
2. Link Vercel project (Softball) with this Github repo (choose Next.js on project type)

It will give Vercel app url address that is deployed on the web. (and automatic deployment on every merge)

Then, I'll connect our softball domain with Vercel's created address.

**Comment by nishi-ai** [comment]
https://softball-register-web.vercel.app/
