### ISSUE TITLE
events are not in order

### ISSUE THREAD

**Issue by benevbright** [nishi-ai/softball-register-web#68]
![Screenshot 2023-02-23 at 22 56 04](https://user-images.githubusercontent.com/916690/221039538-60b573ff-189a-46ca-a123-fcfa2732f6a1.png)

regression bug, somehow the order logic went out? 😁 I believe we had it.

**Comment by nishi-ai** [comment]
fixed with [this commit](https://github.com/nishi-ai/softball-register-web/pull/71/commits/2336051ea3438c2695d21108fe6f53d69609eb1c)
